---

- name: frontend | Install nginx
  yum:
    name: nginx
    state: present

- name: frontend | Ensure nginx is stopped
  service:
    name: nginx
    state: stopped

- name: frontend | Create frontend dir structure
  file:
    path: /home/cbit/{{ item }}
    state: directory
    owner: cbit
    group: cbit
    mode: 0755
  with_items:
    - frontend
    - frontend/public

- name: frontend | Set up error pages
  copy:
    src: "{{ item }}"
    dest: /home/cbit/frontend/public
    owner: cbit
    group: cbit
    mode: 0644
  with_items:
    - 404.html
    - 50x.html

- name: frontend | Setup self-signed SSL cert if we haven't got a real cert
  command: openssl req -x509 -newkey rsa:4096 -keyout {{ ssl_key_path }} -out {{ ssl_cert_path }} -days 365 -nodes -subj '/CN=cbit.maastrichtuniversity.nl'
  args:
    creates: "{{ ssl_cert_path }}"
  when: "{{ gen_self_signed_ssl_cert }}"

# nginx starts up as root, reads the ssl certs, then downgrades to the nginx
# user.  So the safest permissions for these certs are root read-only
- name: frontend | Ensure correct permissions for SSL cert
  file:
    path: /home/cbit/frontend/server.crt
    mode: 0400
    owner: root
    group: root
  when: "{{ gen_self_signed_ssl_cert }}"

- name: frontend | Ensure correct permissions for SSL private key
  file:
    path: /home/cbit/frontend/server.key
    mode: 0400
    owner: root
    group: root
  when: "{{ gen_self_signed_ssl_cert }}"

- name: frontend | Build frontend bundle (locally)
  local_action: command npm run build
  args:
    chdir: "{{ playbook_dir }}/../frontend"
  become: no

- name: frontend | Copy over frontend bundle
  synchronize:
    src: "{{ playbook_dir }}/../frontend/dist/"
    dest: /home/cbit/frontend/public
    owner: no
    group: no
    recursive: yes
    perms: no
    times: yes
    use_ssh_args: yes

- name: frontend | Copy over frontend public assets
  synchronize:
    src: "{{ playbook_dir }}/../frontend/public"
    dest: /home/cbit/frontend/public
    owner: no
    group: no
    recursive: yes
    perms: no
    times: yes
    use_ssh_args: yes

- name: frontend | Ensure proper ownership for front-end bundle
  file:
    path: /home/cbit/frontend/public
    owner: cbit
    group: cbit
    recurse: yes

- name: frontend | Ensure proper permissions for front-end files
  command: find /home/cbit/frontend/public -type f -exec chmod 0644 {} \;

- name: frontend | Ensure proper permissions for front-end directories
  command: find /home/cbit/frontend/public -type d -exec chmod 0755 {} \;


- name: frontend | Configure nginx
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: 0644

- name: frontend | Start and enable nginx
  service:
    name: nginx
    state: started
    enabled: yes