---

- name: frontend | Install nginx
  yum:
    name: nginx
    state: present

- name: frontend | Ensure nginx is stopped
  service:
    name: nginx
    state: stopped

- name: frontend | Create frontend dir structure
  file:
    path: /home/cbit/{{ item }}
    state: directory
    owner: cbit
    group: cbit
    mode: 0755
  with_items:
    - frontend
    - frontend/public

- name: frontend | Set up error pages
  copy:
    src: "{{ item }}"
    dest: /home/cbit/frontend/public
    owner: cbit
    group: cbit
    mode: 0644
  with_items:
    - 404.html
    - 50x.html

- name: frontend | Setup self-signed SSL cert (TODO - Get real cert from Pieter)
  command: openssl req -x509 -newkey rsa:4096 -keyout server.key -out server.crt -days 365 -nodes -subj '/CN=cbit.maastrichtuniversity.nl'
  args:
    chdir: /home/cbit/frontend
    creates: server.crt

- name: frontend | Ensure correct permissions for SSL cert
  file:
    path: /home/cbit/frontend/server.crt
    mode: 0644
    owner: cbit
    group: cbit

- name: frontend | Ensure correct permissions for SSL private key
  file:
    path: /home/cbit/frontend/server.key
    mode: 0640
    owner: cbit
    group: nginx   # `cbit` can change, `nginx` can read, nobody else can do anything

#- name: Build frontend bundle
#  <local>  cd frontend; npm run build

- name: frontend | Copy over frontend bundle
  synchronize:
    src: "{{ playbook_dir }}/../frontend/dist/"
    dest: /home/cbit/frontend/public
    owner: no
    group: no
    recursive: yes
    perms: no
    times: yes
    use_ssh_args: yes

- name: frontend | Copy over frontend public assets
  synchronize:
    src: "{{ playbook_dir }}/../frontend/public"
    dest: /home/cbit/frontend/public
    owner: no
    group: no
    recursive: yes
    perms: no
    times: yes
    use_ssh_args: yes

- name: frontend | Ensure proper ownership for front-end bundle
  file:
    path: /home/cbit/frontend/public
    owner: cbit
    group: cbit
    recurse: yes

- name: frontend | Ensure proper permissions for front-end files
  command: find /home/cbit/frontend/public -type f -exec chmod 0644 {} \;

- name: frontend | Ensure proper permissions for front-end directories
  command: find /home/cbit/frontend/public -type d -exec chmod 0755 {} \;


- name: frontend | Configure nginx
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: 0644

- name: frontend | Start and enable nginx
  service:
    name: nginx
    state: started
    enabled: yes