---

- name: frontend | Install nginx
  yum:
    name: nginx
    state: present

- name: frontend | Ensure nginx is stopped
  service:
    name: nginx
    state: stopped

- name: frontend | Create frontend dir structure
  file:
    path: /home/cbit/{{ item }}
    state: directory
    owner: cbit
    group: cbit
    mode: 0755
  with_items:
    - frontend
    - frontend/public

- name: frontend | Set up error pages
  copy:
    src: "{{ item }}"
    dest: /home/cbit/frontend/public
    owner: cbit
    group: cbit
    mode: 0644
  with_items:
    - 404.html
    - 50x.html

- name: frontend | Configure nginx
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: 0644

- name: frontend | Start and enable nginx
  service:
    name: nginx
    state: started
    enabled: yes