import pandas as pd
import psycopg2
import psycopg2.extensions

def connect_to_postgres(): psycopg2.extensions.connection
def read_investigation(f: file) -> dict: ...
def read_study_sample(f: file) -> pd.DataFrame: ...
def read_assay(f: file) -> pd.DataFrame: ...
