import pandas as pd
from .config import Config

def read_investigation(cfg: Config, f: file) -> dict: ...
def flatten_investigation(i: dict) -> dict: ...
def remove_empty_values_in_dict(d: dict) -> dict: ...
def remove_common_prefixes(d: dict) -> dict: ...
def read_study_sample(cfg: Config, f: file) -> pd.DataFrame: ...
def read_assay(cfg: Config, f: file) -> pd.DataFrame: ...
def read_processed_data(cfg: Config, f: file) -> pd.DataFrame: ...
def read_annotations(cfg: Config, f: file) -> pd.DataFrame: ...
