---

- name: backend | Create cbit group
  group:
    name: cbit
    state: present

- name: backend | Create cbit user
  user:
    name: cbit
    group: cbit
    shell: /bin/bash

- name: backend | Tweak permissions of cbit user home folder
  file:
    path: /home/cbit
    state: directory
    mode: 0755
    owner: cbit
    group: cbit

- name: backend | Create backend directory
  file:
    path: /home/cbit/backend
    state: directory
    mode: 0700
    owner: cbit
    group: cbit

- name: backend | Ensure cbit backend is turned off
  service:
    name: cbit-backend
    state: stopped
  ignore_errors: yes

- name: backend | Copy code to server
  synchronize:
    src: "{{ playbook_dir }}/../backend/"
    dest: /home/cbit/backend
    owner: no
    group: no
    recursive: yes
    perms: no
    times: yes
    use_ssh_args: yes
    rsync_opts:
      - "--exclude /.ipynb_checkpoints"
      - "--exclude /files"
      - "--exclude /uploads"
      - "--exclude /downloads"
      - "--exclude /misc"
      - "--exclude /*.log"
      - "--exclude /pidfile.txt"
      - "--exclude *.pyc"
      - "--verbose"

- name: backend | Fix permissions
  file:
    path: /home/cbit/backend
    state: directory
    owner: cbit
    group: cbit
    recurse: yes

- name: backend | Update pip requirements.txt
  copy:
    src: "{{ playbook_dir }}/../requirements.txt"
    dest: /home/cbit
    owner: cbit
    group: cbit
    mode: 0700

- name: backend | Ensure python requirements are satisfied
  pip:
    requirements: requirements.txt
  args:
    chdir: /home/cbit
  environment:
    PATH: "{{ ansible_env.PATH }}:/usr/pgsql-9.5/bin"

- name: Set up DBs (once)
  shell: ./set_up_dbs.py && rm -rf files/ uploads/ downloads/ && touch 00_DBS_CREATED_DO_NOT_REMOVE.txt
  args:
    chdir: /home/cbit/backend
    creates: 00_DBS_CREATED_DO_NOT_REMOVE.txt

# See gunicorn deployment instructions for details
# http://docs.gunicorn.org/en/stable/deploy.html

- name: backend | Install systemd service
  copy:
    src: cbit-backend.service
    dest: /etc/systemd/system/cbit-backend.service
    owner: root
    group: root
    mode: 0644
  register: service

- name: backend | Install systemd socket
  copy:
    src: cbit-backend.socket
    dest: /etc/systemd/system/cbit-backend.socket
    owner: root
    group: root
    mode: 0644
  register: socket

- name: backend | Install systemd tmpfiles descriptor
  copy:
    src: cbit-backend.conf
    dest: /usr/lib/tmpfiles.d/cbit-backend.conf
    owner: root
    group: root
    mode: 0644
  register: tmpfiles

- name: backend | Start and enable cbit-backend service
  service:
    name: cbit-backend
    state: started
    enabled: yes
    daemon-reload: "{{ service|changed or socket|changed or tmpfiles|changed }}"
