---

- name: Install epel-release (extra packages for yum) and update yum cache
  yum:
    name: epel-release
    state: present
    update_cache: yes

- name: Install key packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:
   - git
   - gcc
   - openssl
   - openssl-devel
   - lsof
   - emacs
   - python-devel
   - python-pip
   - libselinux-python

- name: Upgrade pip
  pip:
    name: pip
    state: latest

- name: Disable SELinux (not even enabled in cBiT on-site machine)
  selinux:
    state: disabled
  register: selinux_status

- name: Prompt for restart if needed
  pause:
    prompt: Disabling SELinux completely requires full restart.  Please restart the machine and run this playbook again
  when: selinux_status | changed

- name: timezone | check current timezone
  shell: readlink -f /etc/localtime
  changed_when: 0
  register: current_zone

- name: timezone | Set timezone variables
  command: timedatectl set-timezone {{ timezone }}
  when: current_zone.stdout != '/usr/share/zoneinfo/' + timezone
