---

- name: Install epel-release (extra packages for yum) and update yum cache
  yum:
    name: epel-release
    state: present
    update_cache: yes

- name: Install key packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:
   - git
   - gcc
   - openssl
   - openssl-devel
   - lsof
   - emacs
   - "postgresql{{ postgresql_version_terse }}-devel"
   - python-devel
   - python-pip

- name: Upgrade pip
  pip:
    name: pip
    state: latest

- name: timezone | check current timezone
  shell: readlink -f /etc/localtime
  changed_when: 0
  register: current_zone

- name: timezone | Set timezone variables
  command: timedatectl set-timezone {{ timezone }}
  when: current_zone.stdout != '/usr/share/zoneinfo/' + timezone
