---

- name: Update APT cache
  apt:
    update_cache: yes
    cache_valid_time: "{{ cache_valid_time }}"

- name: Install key packages
  apt:
    name: "{{ item }}"
    state: present
   with_items:
   - git
   - build-essential
   - python-dev
   - python-pip
   