---
# Run this playbook as follows once for a brand new machine
#
#  ANSIBLE_SSH_PIPELINING=0 ansible-playbook playbook-PRERUN.yml
#
# Sometimes even this won't be enough: for Ansible to work well, it needs
# password-less sudo as well.  If all else fails, run `visudo` and manually
# make the following changes:
#
# 1) Comment out the line `Defaults   requiretty` (it should read `# Defaults   requiretty`)
# 2) Add a line at the end like this:
#
#      USERNAME ALL=(ALL) NOPASSWD: ALL
#
#    where USERNAME is replaced by the ssh username specified in the ansible `hosts` file

- hosts: all
  become: yes
  gather_facts: false
  tasks:
    - name: disable requiretty in /etc/sudoers
      replace: regexp="^Defaults\s+requiretty$" replace="# Defaults    requiretty" dest="/etc/sudoers"

