---

- hosts: all
  vars_files:
    - vars.yml

  roles:

  - { role: system-setup, become: yes, tags: [init] }
  - { role: ANXS.postgresql, become: yes, tags: [init] }
  # TODO: Use this official role instead: https://github.com/elastic/ansible-elasticsearch
  - { role: geerlingguy.elasticsearch, become: yes, java_packages: [java-1.8.0-openjdk], tags: [init] }
  - { role: finish-setup, become: yes, tags: [init] }

  - { role: backend, become: yes, tags: [backend] }
  - { role: frontend, become: yes, tags: [frontend] }