---

- hosts: cbit
  vars_files:
    - vars.yml

  roles:
  - { role: system-setup, become: yes }
  - { role: ANXS.postgresql, become: yes }

  # TODO: Use this official role instead: https://github.com/elastic/ansible-elasticsearch
  - { role: geerlingguy.java, become: yes, java_packages: [openjdk-8-jdk] }
  - { role: geerlingguy.elasticsearch, become: yes }
