---
apt_cache_valid_time: 300    # Time between calls to `apt-get update`

db_name: cbit
db_user: cbit
db_pass: 2076a675b6d813b582977189c13a3279cc9cf02a9aeab01389798d9167cf259c8b247aee9a2be149  # `openssl rand -hex 40`

postgresql_version: 9.5

postgresql_databases:
  - name: "{{db_name}}"
    owner: "{{db_user}}"

postgresql_users:
  - name: "{{db_user}}"
    pass: "{{db_pass}}"

postgresql_user_privileges:
  - name: "{{db_user}}"
    db: "{{db_name}}"

elasticsearch_cluster_name: cbit.elasticsearch.cluster
elasticsearch_timezone: "Europe/Brussels"
elasticsearch_service_startonboot: yes
