---
timezone: "Europe/Amsterdam"

db_name: cbit
db_user: cbit
db_pass: 2076a675b6d813b582977189c13a3279cc9cf02a9aeab01389798d9167cf259c8b247aee9a2be149  # `openssl rand -hex 40`

postgresql_version: 9.5

# For use outside ANXS.postgresql role
postgresql_version_terse: "{{ postgresql_version | replace('.', '') }}"

postgresql_databases:
  - name: "{{db_name}}"
    owner: "{{db_user}}"

postgresql_users:
  - name: "{{db_user}}"
    pass: "{{db_pass}}"

postgresql_user_privileges:
  - name: "{{db_user}}"
    db: "{{db_name}}"


elasticsearch_cluster_name: cbit.elasticsearch.cluster

# Set up long timeouts to handle uploads of large files
request_timeout_s: 600

# For fake certs
gen_self_signed_ssl_cert: yes
ssl_cert_path: /home/cbit/frontend/server.crt
ssl_key_path: /home/cbit/frontend/server.key


# For real certs TODO @MT
#gen_self_signed_ssl_cert: no
#ssl_cert_path: /etc/ssl/cbit_maastrichtuniversity_nl.pem
#ssl_key_path: /etc/ssl/cbit.maastrichtuniversity.nl.key
