from falcon import Request, Response
from data.filters import FiltersState

class MetadataAllCountsResource(object):
    def on_get(self, req: Request, resp: Response): ...

class MetadataFilteredCountsResource(object):
    def on_post(self, req: Request, resp: Response): ...

    def buildESQueryEnumerateControls(self, filters: FiltersState) -> dict: ...
    def extractControlIdsFromResultOfESQueryEnumerateControls(self, esResult: dict) -> list[str]: ...
    def buildESQueryPieces(self, filters: FiltersState, controlStudyIds: list[str]) -> ESQueryPieces: ...

class ESQueryPieces(object):
    def __init__(self, shouldClauses: list[dict], mustClause: dict[str, dict], mustNotClause: dict[str, dict]): ...

class MetadataSamplesInStudies(object):
    def on_post(self, req: Request, resp: Response): ...