from falcon import Request, Response

class StudiesResource(object):
    def on_get(self, req: Request, resp: Response): ...
    def on_post(self, req: Request, resp: Response): ...

class StudyResource(object):
    def on_delete(self, req: Request, resp: Response, study_uuid: str): ...
